name: Update LicenseDB with latest updates from scancode-toolkit develop daily
on:
  schedule:
    - cron: '0 16 * * 1-5'
  workflow_dispatch:

jobs:
  update_licenseDB:
    name: Daily LicenseDB Update
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Run script
        run: ./etc/scripts/check_commit_run_update.sh

      - name: Commit and Push to Publish
        run: |
          git config --global user.name 'LicenseDB Update GitHub Action'
          git config --global user.email 'asmahapatra@nexb.com'
          git add docs/* etc/*
          git commit -m "Automated LicenseDB update with latest from scancode-toolkit develop"
          git push
